import { GoogleGenAI } from "@google/genai";

// Initialize the client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Converts a File object to a Base64 string.
 */
export const fileToGenerativePart = async (file: File): Promise<{ inlineData: { data: string; mimeType: string } }> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
      const base64Data = base64String.split(',')[1];
      resolve({
        inlineData: {
          data: base64Data,
          mimeType: file.type,
        },
      });
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

/**
 * Sends the image to Gemini to remove watermarks.
 */
export const removeWatermark = async (file: File, instruction: string): Promise<string> => {
  try {
    const imagePart = await fileToGenerativePart(file);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          {
            text: `${instruction}. Return the image with watermarks, logos, and text overlays removed. Ensure high quality and preservation of original details.`
          }
        ]
      }
    });

    // Extract the image from the response
    let processedImageBase64 = '';

    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          processedImageBase64 = part.inlineData.data;
          break; // Found the image
        }
      }
    }

    if (!processedImageBase64) {
      throw new Error("No image generated by the model.");
    }

    return `data:image/png;base64,${processedImageBase64}`;
  } catch (error) {
    console.error("Error removing watermark:", error);
    throw error;
  }
};